[package]
name = "reminder_list"
version = "0.0.0"

[addresses]
# Std = "0x1"
Std = "_"

[dependencies]
AptosFramework = { local = "/Users/wujiu/Develop/Project/Aptos/aptos-core/aptos-move/framework/aptos-framework" }
